services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    ports:
      - "3000:8080"
    volumes:
      - ./ollama:/root/.ollama
      - ./open-webui:/app/backend/data
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1'] # Šeit norādi specifisko GPU ID 0 vai 1
              capabilities:
                - gpu

volumes:
  ollama:
  open-webui:
